name: "save-images"
version: "0.0.1"
usage: "helm save-images -f <values.yaml> <chart>"
description: "Run save-images on Helm charts to download and save all docker images to your local filesystem."
command: "$HELM_PLUGIN_DIR/bin/helm-save-images"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/install-binary.sh"
